services:
  streamlit:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8501:8501'
    volumes:
      - './data:/usr/src/app/data'
      - './project:/usr/src/app/project'
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - OLLAMA_URL=http://ollama:11434
    networks:
      - llm_network

  ollama:
    volumes:
        - ollama:/root/.ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    networks:
      - llm_network

volumes:
  ollama:

networks:
  llm_network:
    driver: bridge
